[package]
name = "neighbor"
version = "0.1.0"
authors = ["janus <emekamicro@gmail.com>"]

[dependencies]
bytes = "0.4.0"
edcert = "*"
base64 = "0.6.0"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
